name: Build and Publish Tailspin.SpaceGame.Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ----------------- 1️⃣ BUILD JOB -----------------
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Change to 6.0.x/7.0.x if needed

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj

      # 4. Build project
      - name: Build project
        run: dotnet build ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj --configuration Release --no-restore

      # 5. Run tests (optional)
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal || echo "No tests found"

  # ----------------- 2️⃣ PUBLISH JOB -----------------
  publish:
    name: Publish App
    runs-on: ubuntu-latest
    needs: build  # ✅ runs only if build succeeds
    steps:
      # 1. Checkout repository again
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Restore, Build, and Publish again
      - name: Restore dependencies
        run: dotnet restore ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj

      - name: Build project
        run: dotnet build ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj \
               --configuration Release \
               --output ./publish

      # 4. Upload published output as artifact (optional but useful)
      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-output
          path: ./publish
