name: Build and Publish Tailspin.SpaceGame.Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj

      - name: Build project
        run: dotnet build ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal || echo "No tests found"

  publish:
    name: Publish App
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj

      - name: Build project
        run: dotnet build ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj --configuration Release --output ./publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-output
          path: ./publish
