name: Build, Publish, and Deploy to Azure VM1

on:
  push:
    branches: [ main ]

jobs:
  build_publish_deploy:
    name: Build, Publish & Deploy
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3️⃣ Restore & Build
      - name: Restore dependencies
        run: dotnet restore ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj

      - name: Build project
        run: dotnet build ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj --configuration Release --no-restore

      # 4️⃣ (Optional) Run Tests
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal || echo "No tests found"

      # 5️⃣ Publish Project
      - name: Publish project
        run: dotnet publish ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj --configuration Release --output ./publish

      # 6️⃣ Setup SSH Key for Deployment
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      # 7️⃣ Deploy Files to Azure VM
      - name: Deploy files to VM
        run: |
          echo "Deploying published files to VM..."
          rsync -avz ./publish/ ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/${{ secrets.VM_USER }}/app

      # 8️⃣ Restart Application on VM
      - name: Restart Application
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          echo "Stopping old app (if running)..."
          pkill -f "dotnet Tailspin.SpaceGame.Web.dll" || true
          echo "Starting new app..."
          nohup dotnet /home/${{ secrets.VM_USER }}/app/Tailspin.SpaceGame.Web.dll > app.log 2>&1 &
          EOF
